# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 07:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=datetime.datetime(2018, 5, 11, 9, 44, 31, 256033))),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('observaciones', models.CharField(blank=True, max_length=4000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('image', models.ImageField(blank=True, default='', upload_to='cliente')),
                ('nombre', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=5)),
                ('tipo_via', models.CharField(choices=[('CALLE', 'CALLE'), ('AVENIDA', 'AVENIDA'), ('PLAZA', 'PLAZA')], max_length=10)),
                ('direccion', models.CharField(max_length=200)),
                ('portal', models.IntegerField()),
                ('escalera', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('piso', models.IntegerField()),
                ('casa', models.CharField(default='', max_length=10)),
                ('localidad', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=200)),
                ('telefono1', models.CharField(max_length=9)),
                ('telefono2', models.CharField(max_length=9, null=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('token', models.CharField(db_index=True, max_length=15, null=True, unique=True, verbose_name='Token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_codigo', models.CharField(max_length=12)),
                ('prod_nombre', models.CharField(max_length=120)),
                ('prod_descripcion_corta', models.CharField(max_length=250)),
                ('prod_pvp', models.FloatField(default=0)),
                ('prod_pvp_socio', models.FloatField(default=0)),
                ('prod_categoria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('cli_dni', models.CharField(max_length=9)),
                ('cli_nombre', models.CharField(max_length=80)),
                ('cli_apellidos', models.CharField(max_length=100)),
                ('cli_cp', models.CharField(max_length=5)),
                ('cli_tipo_via', models.CharField(max_length=50)),
                ('cli_direccion', models.CharField(max_length=200)),
                ('cli_portal', models.IntegerField()),
                ('cli_escalera', models.CharField(max_length=10, null=True)),
                ('cli_piso', models.IntegerField()),
                ('cli_casa', models.CharField(max_length=10, null=True)),
                ('cli_localidad', models.CharField(max_length=200)),
                ('cli_provincia', models.CharField(max_length=200)),
                ('cli_telefono1', models.CharField(max_length=9)),
                ('cli_telefono2', models.CharField(max_length=9, null=True)),
                ('cli_email', models.EmailField(default='', max_length=254, unique=True)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2018, 5, 11, 9, 44, 31, 259034))),
                ('subtotal', models.FloatField()),
                ('impuesto', models.FloatField()),
                ('importe_total', models.FloatField()),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermercadoApp.DetalleFactura')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mensaje', models.CharField(choices=[('Opinión', 'Opinión'), ('Duda', 'Duda'), ('Aclaración', 'Aclaración'), ('Reclamación', 'Reclamación')], default='Opinión', max_length=11)),
                ('mensaje', models.CharField(max_length=4000)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2018, 5, 11, 9, 44, 31, 258035))),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermercadoApp.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('image', models.ImageField(blank=True, default='', upload_to='admin')),
                ('cp', models.CharField(max_length=5)),
                ('tipo_via', models.CharField(choices=[('CALLE', 'CALLE'), ('AVENIDA', 'AVENIDA'), ('PLAZA', 'PLAZA')], max_length=10)),
                ('direccion', models.CharField(max_length=200)),
                ('portal', models.IntegerField()),
                ('escalera', models.CharField(blank=True, max_length=10, null=True)),
                ('piso', models.IntegerField()),
                ('casa', models.CharField(max_length=10)),
                ('localidad', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=200)),
                ('telefono1', models.CharField(max_length=9)),
                ('telefono2', models.CharField(max_length=9, null=True)),
                ('token', models.CharField(db_index=True, max_length=15, null=True, unique=True, verbose_name='Token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=4000)),
                ('descripcion_corta', models.CharField(max_length=250)),
                ('imagen', models.ImageField(blank=True, default='', upload_to='productos')),
                ('stock', models.IntegerField(default=0)),
                ('pvp', models.FloatField(default=0)),
                ('pvp_socio', models.FloatField(default=0)),
                ('diferencia_en_tarjeta', models.BooleanField(default=False)),
                ('ean13', models.ImageField(blank=True, default='', upload_to='productos/ean13')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermercadoApp.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('importe_total', models.FloatField(default=0)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermercadoApp.Carrito')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermercadoApp.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIF', models.CharField(max_length=9, unique=True)),
                ('responsable', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=4000)),
                ('telefono1', models.CharField(max_length=9)),
                ('tiene_parking', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tarjeta', models.CharField(default='0', max_length=50, unique=True)),
                ('fecha_adquisicion', models.DateTimeField(default=datetime.datetime(2018, 5, 11, 9, 44, 31, 256033))),
                ('saldo_actual', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermercadoApp.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Supermercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supermercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermercadoApp.Supermercado')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermercadoApp.Cliente'),
        ),
    ]
