# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-12 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercadoApp', '0011_auto_20180511_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 12, 10, 29, 36, 730441)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 12, 10, 29, 36, 731971)),
        ),
        migrations.AlterField(
            model_name='mensaje_cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 12, 10, 29, 36, 728774)),
        ),
        migrations.AlterField(
            model_name='mensaje_cliente',
            name='mensaje',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_adquisicion',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 12, 10, 29, 36, 730103)),
        ),
    ]
