# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 09:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercadoApp', '0015_auto_20180515_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='prod_iva',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 11, 43, 33, 162978)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 11, 43, 33, 163978)),
        ),
        migrations.AlterField(
            model_name='mensaje_cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 11, 43, 33, 159976)),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_adquisicion',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 11, 43, 33, 161977)),
        ),
    ]
