# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 12:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercadoApp', '0016_auto_20180515_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 14, 55, 4, 558712)),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='image',
            field=models.ImageField(blank=True, default='cliente/default.png', upload_to='cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 14, 55, 4, 559712)),
        ),
        migrations.AlterField(
            model_name='mensaje_cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 14, 55, 4, 555710)),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_adquisicion',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 14, 55, 4, 557714)),
        ),
    ]
