# Generated by Django 2.0.5 on 2018-05-17 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercadoApp', '0018_auto_20180517_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='prod_pvp_socio',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 17, 17, 26, 20, 711917)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 17, 17, 26, 20, 712788)),
        ),
        migrations.AlterField(
            model_name='mensaje_cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 17, 17, 26, 20, 709588)),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_adquisicion',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 17, 17, 26, 20, 710986)),
        ),
    ]
