# Generated by Django 2.0.5 on 2018-05-17 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercadoApp', '0019_auto_20180517_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cli_socio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 17, 19, 56, 2, 194380)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 17, 19, 56, 2, 195323)),
        ),
        migrations.AlterField(
            model_name='mensaje_cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 17, 19, 56, 2, 192086)),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_adquisicion',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 17, 19, 56, 2, 194031)),
        ),
    ]
