# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 12:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercadoApp', '0006_auto_20180511_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 11, 14, 12, 42, 855055)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 11, 14, 12, 42, 855055)),
        ),
        migrations.AlterField(
            model_name='mensaje_cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 11, 14, 12, 42, 839428)),
        ),
        migrations.AlterField(
            model_name='mensajeproducto',
            name='estado_mensaje',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='En espera', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_adquisicion',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 11, 14, 12, 42, 855055)),
        ),
    ]
