# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 07:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermercadoApp', '0014_auto_20180515_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 9, 5, 31, 650739)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cli_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 9, 5, 31, 652741)),
        ),
        migrations.AlterField(
            model_name='mensaje_cliente',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 9, 5, 31, 648738)),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_adquisicion',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 9, 5, 31, 650739)),
        ),
    ]
